POST http://localhost:8080/players
Content-Type: application/json

{
  "buildings": [
    {
      "id": 1,
      "name": "Windmill",
      "wood": 20,
      "gold": 15,
      "food": 10
    },
    {
      "id": 2,
      "name": "Cottage",
      "wood": "100",
      "gold": 150,
      "food": 50
    },
    {
      "id": 3,
      "name": "Bakery",
      "wood": 210,
      "gold": 250,
      "food": 100
    }
  ],
  "resources" : [
    {
      "resource name" : "wood",
      "quantity" :1000
    }

  ]

}
###create craft pattern
POST http://localhost:8080//craft