###add player
POST http://localhost:8080/players
Content-Type: application/json

{
  "craft elements": [
    {
      "craftElementId": 1,
      "craftElementName": "wood",
     "quantity" : 35
    },
    {
      "craftElementId": 2,
      "craftElementName": "stone",
      "quantity": 30

    },
    {
      "craftElementId": 3,
      "craftElementName": "glass",
      "quantity": 50
    },
    {
      "craftElementId": 4,
      "craftElementName": "brick",
      "quantity" : 50
    }
  ],
 "gold" : 5000
}

###create building by the receipt
POST http://localhost:8080/player/1/buildings?receiptId=1
Content-Type: application/json

###get player
GET http://localhost:8080/player/1
Accept: application/json

###add building house

POST http://localhost:8080/buildings
Content-Type: application/json

{
  "id" : 1,
  "name" : "house",
  "price" : 50,
  "amt" : 1
}

###update building house
POST http://localhost:8080/buildings/2
Content-Type: application/json

{
  "id" : 2,
  "price" : 20
}
###add the receipt of cottage
POST http://localhost:8080/receipts
Content-Type: application/json

{
  "name": "wooden cottage",
  "craftElementList": [
    {
      "craftElementId": 1,
      "craftElementName": "wood",
      "quantity": 10
    },
    {
      "craftElementId": 4,
      "craftElementName": "brick",
      "quantity": 20
    },
    {
      "craftElementId" : 3,
      "craftElementName" : "glass",
      "quantity" : 15
    }
    ],
  "price" : 200
  }